name: Check Upstream Updates

on:
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_update: ${{ steps.compare.outputs.has_update }}
      upstream_sha: ${{ steps.fetch.outputs.sha }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch upstream commit
        id: fetch
        run: |
          UPSTREAM_SHA=$(git ls-remote https://github.com/Unmanic/unmanic.git HEAD | awk '{print $1}')
          echo "sha=$UPSTREAM_SHA" >> $GITHUB_OUTPUT
          echo "Upstream SHA: $UPSTREAM_SHA"

      - name: Read current SHA
        id: current
        run: |
          if [ -f .upstream-sha ]; then
            CURRENT_SHA=$(cat .upstream-sha)
          else
            CURRENT_SHA="none"
          fi
          echo "sha=$CURRENT_SHA" >> $GITHUB_OUTPUT
          echo "Current SHA: $CURRENT_SHA"

      - name: Compare
        id: compare
        run: |
          if [ "${{ steps.fetch.outputs.sha }}" != "${{ steps.current.outputs.sha }}" ]; then
            echo "has_update=true" >> $GITHUB_OUTPUT
            echo "✓ Update available"
          else
            echo "has_update=false" >> $GITHUB_OUTPUT
            echo "✓ Up to date"
          fi

      - name: Trigger update
        if: steps.compare.outputs.has_update == 'true'
        run: |
          gh workflow run update-code.yml \
            -f upstream_sha="${{ steps.fetch.outputs.sha }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
