name: Check for new upstream tag

on:
  schedule:
    - cron: "0 6 * * *"  # Todos los días a las 6 AM UTC
  workflow_dispatch:

jobs:
  check-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch latest upstream tag
        id: upstream
        run: |
          git clone --branch master --tags https://github.com/Unmanic/unmanic.git unmanic-temp
          cd unmanic-temp
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest upstream tag: $LATEST_TAG"
          cd ..
          rm -rf unmanic-temp

      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Get last synced tag
        id: local
        run: |
          LAST_TAG_FILE=".last_upstream_tag"
          if [ -f "$LAST_TAG_FILE" ]; then
            LAST_TAG=$(cat "$LAST_TAG_FILE")
          else
            LAST_TAG="none"
          fi
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
          echo "Last synced tag: $LAST_TAG"

      - name: Compare tags
        id: compare
        run: |
          if [ "$LATEST_TAG" != "$LAST_TAG" ]; then
            echo "new_tag=true" >> $GITHUB_OUTPUT
          else
            echo "new_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger update workflow
        if: steps.compare.outputs.new_tag == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_REPO_DISPATCH }}
          repository: JMVS/FOSSmaniac
          event-type: trigger-upstream-update

      - name: Save latest tag
        if: steps.compare.outputs.new_tag == 'true'
        run: |
          echo "$LATEST_TAG" > .last_upstream_tag
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .last_upstream_tag
          git commit -m "Track upstream tag $LATEST_TAG"
          git push
