name: Check Upstream Updates

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: write      # ← Agregar esto

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch upstream commit
        id: fetch
        run: |
          UPSTREAM_SHA=$(git ls-remote https://github.com/Unmanic/unmanic.git HEAD | awk '{print $1}')
          echo "sha=$UPSTREAM_SHA" >> $GITHUB_OUTPUT
          echo "Upstream SHA: $UPSTREAM_SHA"

      - name: Read current SHA
        id: current
        run: |
          if [ -f .upstream-sha ]; then
            CURRENT_SHA=$(cat .upstream-sha)
          else
            CURRENT_SHA="none"
          fi
          echo "sha=$CURRENT_SHA" >> $GITHUB_OUTPUT
          echo "Current SHA: $CURRENT_SHA"

      - name: Compare and trigger update
        if: steps.fetch.outputs.sha != steps.current.outputs.sha
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Update available!');
            console.log('Current:', '${{ steps.current.outputs.sha }}');
            console.log('Upstream:', '${{ steps.fetch.outputs.sha }}');
            
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'upstream_update',
              client_payload: {
                upstream_sha: '${{ steps.fetch.outputs.sha }}'
              }
            });
            
            console.log('✓ Update event dispatched');
